- src/main/java/com/beautiflow/global/common/config/SecurityConfig.java
- src/main/java/com/beautiflow/global/common/config/SwaggerConfig.java
- src/main/java/com/beautiflow/global/common/security/CustomOAuth2User.java
> [REFACT] 스웨거 공통 추가 설정 by 로그인

- .github/workflows/deploy.yml
- src/main/java/com/beautiflow/shop/controller/ShopController.java
> workflow 수정

- src/main/java/com/beautiflow/shop/domain/ShopMember.java
- src/main/java/com/beautiflow/user/domain/User.java
- src/main/java/com/beautiflow/user/domain/UserStyle.java
- src/main/java/com/beautiflow/user/domain/UserStyleImage.java
#68 
UserStyle, UserStyleImage 분리
User에 intro삭제 & email필드 도입
ShopMember에 intro추가, 프로필 이미지 관련 필드 추가
> [REFACT] UserStyle등 엔티티 수정

- .github/workflows/deploy.yml
> matrix secrets 참조 수정

- .github/workflows/deploy.yml
> upload artifact 버전 오류 수정

- src/main/resources/application-prod.yml
- src/main/resources/application.yml
#67
배포용 yaml 파일(application-prod.yml) 생성
> [FEAT] application-prod 추가

- src/main/resources/application-test.yml
> test yml aws 설정 추가

- .github/workflows/deploy.yml
> deploy 환경변수 주입

- .github/workflows/deploy.yml
> artifact 보고서 추가

- .github/workflows/deploy.yml
> package download 버전 수정

- .github/workflows/deploy.yml
> ssh key flow 수정

- .github/workflows/deploy.yml
> deploy.yml server type 추가

- .github/workflows/deploy.yml
- scripts/deploy.sh
> healthcheck 경로 수정

- build.gradle
- src/main/resources/application-prod.yml
- src/main/resources/application-test.yml
- src/main/resources/application.yml
- src/test/java/com/beautiflow/BeautiflowApplicationTests.java
> build test 오류 수정

- src/main/resources/application-prod.yml
> jwt validity 설정

- .github/workflows/deploy.yml
> cache 임시 비활성화

- src/main/java/com/beautiflow/BeautiflowApplication.java
> repository 스캔 경로 추가

- src/main/java/com/beautiflow/BeautiflowApplication.java
- src/main/resources/application-prod.yml
> gateway yml 설정 수정, 이전 commit 롤백

- src/main/resources/application-prod.yml
> prod yml 수정

- src/main/java/com/beautiflow/global/common/security/filter/JWTFilter.java
- src/main/java/com/beautiflow/reservation/repository/ReservationRepository.java
> [FIX]충돌 해결 후 컴파일에러 해결

- src/main/resources/application-prod.yml
> redis ssl 설정 추가

- src/main/java/com/beautiflow/global/common/security/authentication/CustomSuccessHandler.java
> success handler set cookie 수정

- build.gradle
- src/main/java/com/beautiflow/chat/service/ChatRoomService.java
- src/main/java/com/beautiflow/global/common/error/AuthErrorCode.java
- src/main/java/com/beautiflow/global/common/sms/SmsProperties.java
- src/main/java/com/beautiflow/global/common/sms/SmsService.java
- src/main/java/com/beautiflow/user/controller/PhoneAuthController.java
- src/main/java/com/beautiflow/user/dto/PhoneAuthReq.java
- src/main/java/com/beautiflow/user/dto/VerifyCodeReq.java
- src/main/java/com/beautiflow/user/service/PhoneAuthService.java
- src/main/resources/application-prod.yml
> [FEAT] cool sms

- src/main/java/com/beautiflow/chat/config/StompWebSocketConfig.java
- src/main/java/com/beautiflow/global/common/config/SecurityConfig.java
> [REFACT] config 설정 추가

- src/main/java/com/beautiflow/global/common/security/authentication/CustomSuccessHandler.java
> [REFACT] Redirect url수정

- src/main/java/com/beautiflow/global/common/security/authentication/CustomSuccessHandler.java
> [REFACT] successHandler수정

- scripts/deploy.sh
> deploy.sh host header 추가

- scripts/deploy.sh
> 배포 디버깅 코드 추가

- src/main/resources/application-prod.yml
> [REFACT] 개발용 액세스토큰 유효기간 설정

- src/main/java/com/beautiflow/chat/controller/ChatImageController.java
- src/main/java/com/beautiflow/chat/domain/ChatMessage.java
> [REFACT] 이미지 전송 수정

- src/main/java/com/beautiflow/global/common/config/SecurityConfig.java
> [REFACT] security config에 redirect url 추가

- src/main/java/com/beautiflow/shop/controller/ShopManageController.java
> [REFACT] 샵 정보 수정 api 오류 수정

- src/main/java/com/beautiflow/shop/controller/ShopManageController.java
> 재배포 위한 commit

- src/main/java/com/beautiflow/global/common/security/authentication/CustomSuccessHandler.java
> [REFACT] redirecturl수정

- src/main/java/com/beautiflow/global/common/config/SecurityConfig.java
> [REFACT] 비 로그인 api path 허용

- src/main/java/com/beautiflow/reservation/config/SchedulingConfig.java
> [FEAT] 고객리스트자동추가 job 추가

- src/main/java/com/beautiflow/ManagedCustomer/controller/ManagedCustomerController.java
- src/main/java/com/beautiflow/ManagedCustomer/domain/ManagedCustomer.java
- src/main/java/com/beautiflow/ManagedCustomer/dto/CustomerUpdateReq.java
- src/main/java/com/beautiflow/ManagedCustomer/service/ManagedCustomerService.java
> [DOCS] 고객정보수정 응닶값 수정

- src/main/java/com/beautiflow/reservation/domain/TempReservation.java
- src/main/java/com/beautiflow/reservation/dto/request/RequestNotesStyleReq.java
- src/main/java/com/beautiflow/reservation/service/ReservationService.java
#192 
레퍼런스 사진 업로드 파일 -> url 형식 변환 추가
- [✅ ] 코드가 정상적으로 컴파일되나요?
- [✅ ] 테스트 코드를 통과했나요?
- [✅ ] merge할 브랜치의 위치를 확인했나요?
- [✅ ] Label을 지정했나요?
> [FIX] 레퍼런스 사진 업로드 파일 -> url 형식 변환 추가

- src/main/java/com/beautiflow/shop/controller/ShopManageController.java
> [FIX] api 코드 누락 롤백

- src/main/java/com/beautiflow/ManagedCustomer/dto/CustomerDetailRes.java
#199 
[DOCS] 고객 상세 정보 조회 그룹값추가
- [ ✅] 코드가 정상적으로 컴파일되나요?
- [✅ ] 테스트 코드를 통과했나요?
- [✅ ] merge할 브랜치의 위치를 확인했나요?
- [✅ ] Label을 지정했나요?
> [DOCS] 고객 상세 정보 조회 그룹값추가

- src/main/java/com/beautiflow/ManagedCustomer/controller/ManagedCustomerController.java
- src/main/java/com/beautiflow/ManagedCustomer/dto/CustomerGroupDetailRes.java
- src/main/java/com/beautiflow/ManagedCustomer/repository/CustomerGroupRepository.java
- src/main/java/com/beautiflow/ManagedCustomer/service/CustomerGroupService.java
#203 
고객 그룹 목록 조회 API 제작
- [✅ ] 코드가 정상적으로 컴파일되나요?
- [ ✅] 테스트 코드를 통과했나요?
- [ ✅] merge할 브랜치의 위치를 확인했나요?
- [ ✅] Label을 지정했나요?
> [FEAT] 고객 그룹 목록 조회 API 제작

- src/main/java/com/beautiflow/shop/domain/RegularHoliday.java
- src/main/java/com/beautiflow/shop/dto/RegularHolidayDto.java
- src/main/java/com/beautiflow/shop/service/ShopManageService.java
#196 
매장 정기휴무 요일 중복 선택 가능하도록 수정
> [REFACT] 매장 정기휴무 요일 중복 선택 가능하도록 수정

- src/main/java/com/beautiflow/shop/controller/ShopManageController.java
- src/main/java/com/beautiflow/shop/domain/Shop.java
- src/main/java/com/beautiflow/shop/dto/BusinessHourRes.java
- src/main/java/com/beautiflow/shop/dto/BusinessHourUpdateReq.java
- src/main/java/com/beautiflow/shop/dto/ShopInfoRes.java
- src/main/java/com/beautiflow/shop/dto/ShopUpdateReq.java
- src/main/java/com/beautiflow/shop/service/ShopManageService.java
> [REFACT] 프론트 연결 중 수정사항 반영

- src/main/java/com/beautiflow/global/common/config/RedisConfig.java
- src/main/java/com/beautiflow/shop/repository/ShopMemberRepository.java
- src/main/java/com/beautiflow/user/dto/UserInfoRes.java
- src/main/java/com/beautiflow/user/service/MyPageService.java
> [REFACT] ShopMemberRes 반환 추가

- src/main/java/com/beautiflow/treatment/domain/OptionGroup.java
- src/main/java/com/beautiflow/treatment/domain/OptionItem.java
- src/main/java/com/beautiflow/treatment/domain/Treatment.java
- src/main/java/com/beautiflow/treatment/service/TreatmentService.java
> [FIX] 옵션 그룹 수정/생성 불가 오류 해결

- src/main/java/com/beautiflow/shop/service/ShopOnboardingService.java
> [REFACT] 입사 신청시 자동 승인으로 변경

- src/main/java/com/beautiflow/user/dto/UserInfoRes.java
- src/main/java/com/beautiflow/user/service/MyPageService.java
> [REFACT] data안에 shopId

- src/main/java/com/beautiflow/global/common/config/SecurityConfig.java
> [REFACT] shop 관련 url 수정

- src/main/java/com/beautiflow/user/dto/UserInfoRes.java
- src/main/java/com/beautiflow/user/service/MyPageService.java
> [REFACT]shopMembers응답추가

- src/main/java/com/beautiflow/reservation/dto/response/ReservationStatusRes.java
- src/main/java/com/beautiflow/shop/converter/ShopConverter.java
> [REFACT] shop 및 reservation null 문제 해결
